version: '3.7'
services:
  web:
     build: .
     volumes:
         - ./var/www/html
     ports:
         - 80:80
  db:
        image: mysql
        volumes:
            - ./db_data:/var/lib/mysql
        environment:
           DB_HOST: 'mysql'
           DB_USERNAME: 'root'
           DB_PASSWORD: ''
           DB_NAME: '2520448_armentum'
        ports:
            - 3306:3306










